version: '1'

services:
  frontend:
    build: frontend
    ports:
      - 8501:8501
    volumes:
      - './frontend:/app:delegated'
    depends_on:
      - backend
    
  backend:
    build: backend
    ports:
      - 8000:8000  